services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-service-java
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/backend_java
      - REDIS_URL=redis://host.docker.internal:6379
      - MESSAGING_ENABLED=false
      - RABBIT_URL=amqp://guest:guest@host.docker.internal:5672/
      - HEALTH_CHECK_CRON=*/1 * * * *
      - HEALTH_CHECK_ENABLED=true
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
