quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/backend_java}
quarkus.datasource.jdbc.initial-size=0
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.max-size=5

quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}

%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.redis.devservices.enabled=false
%dev.quarkus.rabbitmqclient.devservices.enabled=false
