CREATE SCHEMA IF NOT EXISTS AUDIT;
CREATE ALIAS IF NOT EXISTS UNACCENT FOR "com.app.utils.H2Functions.unaccent";
CREATE ALIAS IF NOT EXISTS IMMUTABLE_UNACCENT FOR "com.app.utils.H2Functions.unaccent";
